//! CLEANPLATE desktop shell.
//!
//! Wraps the same web workbench (../../frontend/dist) in a native window themed
//! from the shared design tokens (see theme.rs, generated by sync-theme.mjs).
//! The desktop build is licence-key and offline: no account, nothing uploaded.
//! It talks to a local engine at http://localhost:8000 — either an already
//! running `python -m cleanplate`, or the bundled sidecar spawned below.

mod theme;

use serde::Serialize;

#[derive(Serialize)]
struct Theme {
    brand: &'static str,
    tagline: &'static str,
    bg_void: &'static str,
    bg_surface: &'static str,
    accent: &'static str,
    text_hi: &'static str,
}

/// Expose the token-derived theme to the webview if it wants native parity.
#[tauri::command]
fn app_theme() -> Theme {
    Theme {
        brand: theme::BRAND,
        tagline: theme::TAGLINE,
        bg_void: theme::BG_VOID,
        bg_surface: theme::BG_SURFACE,
        accent: theme::ACCENT,
        text_hi: theme::TEXT_HI,
    }
}

/// Offline licence activation stub — perpetual, up to three machines.
/// A real build verifies a signed key against a machine fingerprint and stores
/// the activation locally; here we validate the format only.
#[tauri::command]
fn activate_license(key: String) -> Result<bool, String> {
    let ok = key.len() >= 20 && key.split('-').count() == 4;
    if ok {
        Ok(true)
    } else {
        Err("invalid licence key format".into())
    }
}

pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![app_theme, activate_license])
        .setup(|_app| {
            // Optionally spawn the bundled engine sidecar here, e.g.:
            //   let (_rx, _child) = app.shell()
            //       .sidecar("cleanplate-engine")?.spawn()?;
            // The reference build expects `python -m cleanplate` on :8000.
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running CLEANPLATE");
}
