// GENERATED by desktop/sync-theme.mjs from design/tokens.json — do not edit.
#![allow(dead_code)]
pub const BG_VOID: &str = "#08090B";
pub const BG_SURFACE: &str = "#101216";
pub const ACCENT: &str = "#FFB020";
pub const TEXT_HI: &str = "#ECEEF1";
pub const BRAND: &str = "CLEANPLATE";
pub const TAGLINE: &str = "Remove it. Rebuild it. Ship it.";
