#!/usr/bin/env node
/**
 * CLEANPLATE token generator.
 * Reads design/tokens.json (the single source of truth) and emits:
 *   - design/generated/tokens.css        CSS custom properties, dark default + [data-theme=light] mirror
 *   - design/generated/tailwind-tokens.cjs  a Tailwind `theme.extend` fragment
 *   - design/generated/tauri-theme.json   colors + radii for the Tauri window/native chrome
 *
 * Run:  node design/generate.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const t = JSON.parse(readFileSync(join(here, "tokens.json"), "utf8"));
const outDir = join(here, "generated");
mkdirSync(outDir, { recursive: true });

const varName = (k) => `--${k}`;

function cssBlock(colorSet) {
  return Object.entries(colorSet)
    .map(([k, v]) => `  ${varName(k)}: ${v};`)
    .join("\n");
}

// ---- tokens.css ----------------------------------------------------------
const css = `/* GENERATED by design/generate.mjs — do not edit. Edit design/tokens.json. */
:root {
${cssBlock(t.color.dark)}

  --font-sans: ${t.font.sans};
  --font-mono: ${t.font.mono};

  --fs-11: ${t.fontSize["11"]};
  --fs-12: ${t.fontSize["12"]};
  --fs-13: ${t.fontSize["13"]};
  --fs-15: ${t.fontSize["15"]};
  --fs-18: ${t.fontSize["18"]};
  --fs-24: ${t.fontSize["24"]};
  --fs-32: ${t.fontSize["32"]};
  --fs-48: ${t.fontSize["48"]};

  --lh-body: ${t.lineHeight.body};
  --lh-display: ${t.lineHeight.display};

  --radius-control: ${t.radius.control};
  --radius-card: ${t.radius.card};
  --radius-input: ${t.radius.input};
  --radius-monogram: ${t.radius.monogram};

  --size-control: ${t.size.control};
  --size-input: ${t.size.input};
  --rail: ${t.size.leftRail};
  --right-panel: ${t.size.rightPanel};
  --bottom-bar: ${t.size.bottomBar};
  --grid-max: ${t.size.gridMax};
  --gutter: ${t.size.gutter};

  --motion-ui: ${t.motion.ui};
  --motion-panel: ${t.motion.panel};

  --mask-fill: ${t.mask.fill};
  --mask-alpha: ${t.mask.fillAlpha};

  color-scheme: dark;
}

[data-theme="light"] {
${cssBlock(t.color.light)}
  color-scheme: light;
}
`;
writeFileSync(join(outDir, "tokens.css"), css);

// ---- tailwind-tokens.cjs -------------------------------------------------
const colorMap = {};
for (const key of Object.keys(t.color.dark)) {
  colorMap[key] = `var(${varName(key)})`;
}
const tw = {
  colors: colorMap,
  fontFamily: {
    sans: "var(--font-sans)".split(),
    mono: "var(--font-mono)".split(),
  },
  fontSize: Object.fromEntries(
    Object.entries(t.fontSize).map(([k, v]) => [k, [v, { lineHeight: k >= 24 ? t.lineHeight.display : t.lineHeight.body }]])
  ),
  borderRadius: {
    control: t.radius.control,
    card: t.radius.card,
    input: t.radius.input,
    monogram: t.radius.monogram,
  },
  spacing: {
    rail: t.size.leftRail,
    "right-panel": t.size.rightPanel,
    "bottom-bar": t.size.bottomBar,
    control: t.size.control,
    input: t.size.input,
  },
  letterSpacing: { label: t.label.tracking },
  transitionTimingFunction: { ui: "cubic-bezier(0.2,0,0,1)" },
  maxWidth: { grid: t.size.gridMax },
};
writeFileSync(
  join(outDir, "tailwind-tokens.cjs"),
  `// GENERATED by design/generate.mjs — do not edit. Edit design/tokens.json.\nmodule.exports = ${JSON.stringify(tw, null, 2)};\n`
);

// ---- tauri-theme.json ----------------------------------------------------
const tauri = {
  brand: t.brand,
  dark: t.color.dark,
  light: t.color.light,
  radius: t.radius,
  window: {
    backgroundColor: t.color.dark["bg-void"],
    titleBarColor: t.color.dark["bg-surface"],
  },
};
writeFileSync(join(outDir, "tauri-theme.json"), JSON.stringify(tauri, null, 2) + "\n");

console.log("CLEANPLATE tokens generated ->", outDir);
console.log("  tokens.css, tailwind-tokens.cjs, tauri-theme.json");
