#!/usr/bin/env node
// Consume the shared design tokens for the native shell:
//  - emit src-tauri/src/theme.rs (colors as Rust constants)
//  - patch the window backgroundColor in tauri.conf.json to --bg-void
// Run automatically before `tauri dev` / `tauri build` (see package.json).
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const theme = JSON.parse(readFileSync(join(here, "..", "design", "generated", "tauri-theme.json"), "utf8"));
const d = theme.dark;

const rs = `// GENERATED by desktop/sync-theme.mjs from design/tokens.json — do not edit.
#![allow(dead_code)]
pub const BG_VOID: &str = "${d["bg-void"]}";
pub const BG_SURFACE: &str = "${d["bg-surface"]}";
pub const ACCENT: &str = "${d.accent}";
pub const TEXT_HI: &str = "${d["text-hi"]}";
pub const BRAND: &str = "${theme.brand.name}";
pub const TAGLINE: &str = "${theme.brand.tagline}";
`;
writeFileSync(join(here, "src-tauri", "src", "theme.rs"), rs);

const confPath = join(here, "src-tauri", "tauri.conf.json");
if (existsSync(confPath)) {
  const conf = JSON.parse(readFileSync(confPath, "utf8"));
  if (conf.app?.windows?.[0]) conf.app.windows[0].backgroundColor = d["bg-void"];
  writeFileSync(confPath, JSON.stringify(conf, null, 2) + "\n");
}

console.log("desktop theme synced from tokens:", d["bg-void"]);
